config/routes.rb
Rails.application.routes.draw do
  resources :categories
  get 'welcome/index'
  get '/inicio', to:'welcome#index'
  resources :patientlists

  root to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
 has_many :patientlists
end

app/models/patientlist.rb
class Patientlist < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  def set_locale
    if params[:locale]
      cookies[:locale] = params[:locale]
    end
    if cookies[:locale]
      if I18n.locale != cookies[:locale]
        I18n.locale = cookies[:locale]
      end
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:description)
    end
end

app/controllers/patientlists_controller.rb
class PatientlistsController < ApplicationController
  before_action :set_patientlist, only: %i[ show edit update destroy ]
  before_action :set_category_options, only: %i[new create edit update]

  # GET /patientlists or /patientlists.json
  def index
    @patientlists = Patientlist.all
  end

  # GET /patientlists/1 or /patientlists/1.json
  def show
  end

  # GET /patientlists/new
  def new
    @patientlist = Patientlist.new
  end

  # GET /patientlists/1/edit
  def edit
  end

  # POST /patientlists or /patientlists.json
  def create
    @patientlist = Patientlist.new(patientlist_params)

    respond_to do |format|
      if @patientlist.save
        format.html { redirect_to patientlist_url(@patientlist), notice: "Patientlist was successfully created." }
        format.json { render :show, status: :created, location: @patientlist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @patientlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patientlists/1 or /patientlists/1.json
  def update
    respond_to do |format|
      if @patientlist.update(patientlist_params)
        format.html { redirect_to patientlist_url(@patientlist), notice: "Patientlist was successfully updated." }
        format.json { render :show, status: :ok, location: @patientlist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @patientlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patientlists/1 or /patientlists/1.json
  def destroy
    @patientlist.destroy

    respond_to do |format|
      format.html { redirect_to patientlists_url, notice: "Patientlist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def set_category_options
      @category_options = Category.all.pluck(:description, :id)
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_patientlist
      @patientlist = Patientlist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patientlist_params
      params.require(:patientlist).permit(:register_name, :email, :category_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def data_br(data_us)
    data_us.strftime("%d/%m/%y")
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/patientlists_helper.rb
module PatientlistsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class:"form-control", placeholder:"Digite aqui se você é adulto, idoso, ou criança" %>
  </div>

  <div class="actions">
    <%= form.submit nil, class:"btn btn-primary" %>
  </div>
<% end %>

<br>

app/views/categories/edit.html.erb
<h1><%= t('edit') %></h1>

<%= render 'form', category: @category %>

<%= link_to t('links.show'), @category, class:"btn btn-primary" %> |
<%= link_to t('links.back'), categories_path, class:"btn btn-primary" %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= Category.model_name.human(count:@categories.count) %></h1>

<table class= "table table-hover">
  <thead>
    <tr>
      <th><%= @categories.human_attribute_name(:description) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.description %></td>
        <td><%= link_to t('links.show'), category %></td>
        <td><%= link_to t('links.edit'), edit_category_path(category) %></td>
        <td><%= link_to t('links.destroy'), category, method: :delete, data: { confirm: t('confirm_msg') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('links.new category'), new_category_path, class:"btn btn-primary" %>

app/views/categories/new.html.erb
<h1><%= t('new category') %></h1>

<%= render 'form', category: @category %>

<%= link_to t('links.back'), categories_path, class:"btn btn-primary" %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<form>
  <div class="form-group">
    <%= label_tag nil, @category.class.human_attribute_name(:description) %>
    <%= text_field_tag nil, @category.description, class:"form-control", disabled: true %>
  </div>
</form>
<br>

<%= link_to t('links.edit'), edit_category_path(@category), class:"btn btn-primary" %> |
<%= link_to t('links.back'), categories_path, class:"btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>List</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    params[:controller], media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag params[:controller], 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
          <ul class="nav justify-content-end">
            <li class="nav-item">
              <%= link_to '[HOME]', root_path, class:"nav-link active"  %>
            </li>
            <li class="nav-item">
              <%= link_to 'Português', root_path(locale:'pt-BR'), class:"nav-link active"  %>
            </li>
            <li class="nav-item">
              <%= link_to 'English', root_path(locale:'en'), class:"nav-link"  %>
            </li>
          </ul>
      <%= yield %>
    </div>
  </body>
</html>

app/views/patientlists/_form.html.erb
<%= form_with(model: patientlist, local: true) do |form| %>
  <% if patientlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patientlist.errors.count, "error") %> prohibited this patientlist from being saved:</h2>

      <ul>
      <% patientlist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :register_name %>
    <%= form.text_field :register_name, class:"form-control", placeholder:"Digite aqui seu nome" %>
  </div>
  
  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, type:"email", class:"form-control", placeholder:"Enter email" %>
  </div>
  
  <div class="form-group">
    <%= form.label :category_id %>
    <%= form.select("category_id", @category_options, { include_blank: t('select')},class:"form-control") %>
  </div>

  <div class="actions">
    <%= form.submit nil, class:"btn btn-primary" %>
  </div>
<% end %>

<br>

app/views/patientlists/edit.html.erb
<h1><%= t('edit') %></h1>

<%= render 'form', patientlist: @patientlist %>

<%= link_to t('links.show'), @patientlist, class:"btn btn-primary" %> |
<%= link_to t('links.back'), patientlists_path, class:"btn btn-primary" %>

app/views/patientlists/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= Patientlist.model_name.human(count:@patientlists.count) %></h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th><%= @patientlists.human_attribute_name(:register_name) %></th>
      <th><%= @patientlists.human_attribute_name(:email) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patientlists.each do |patientlist| %>
      <tr>
        <td><%= patientlist.register_name %></td>
        <td><%= patientlist.email %></td>
        <td><%= link_to t('links.show'), patientlist %></td>
        <td><%= link_to t('links.edit'), edit_patientlist_path(patientlist) %></td>
        <td><%= link_to t('links.destroy'), patientlist, method: :delete, data: { confirm: t('confirm_msg') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('links.new patientlist'), new_patientlist_path, class:"btn btn-primary" %>

app/views/patientlists/new.html.erb
<h1><%= t('new patientlist') %></h1>

<%= render 'form', patientlist: @patientlist %>

<%= link_to t('links.back'), patientlists_path, class:"btn btn-primary" %>

app/views/patientlists/show.html.erb
<p id="notice"><%= notice %></p>

<form>
  <div class="form-group">
    <%= label_tag nil, @patientlist.class.human_attribute_name(:register_name) %>
    <%= text_field_tag nil, @patientlist.register_name, class:"form-control", disabled: true %>
  </div>
  
  <div class="-group">
    <%= label_tag nil, @patientlist.class.human_attribute_name(:email) %>
    <%= text_field_tag nil, @patientlist.email, class:"form-control", disabled: true %>
  </div>
  <br>
  <div class="-group">
    <%= label_tag nil, @patientlist.class.human_attribute_name(:category) %>
    <%= text_field_tag nil, @patientlist.category.description, class:"form-control", disabled: true %>
  </div>
</form>
<br>

<%= link_to t('links.edit'), edit_patientlist_path(@patientlist), class:"btn btn-primary" %> |
<%= link_to t('links.back'), patientlists_path, class:"btn btn-primary" %>

app/views/welcome/_menu.html.erb
<%= link_to t('links.register'), patientlists_path, class:"btn btn-primary btn-lg", role:"button" %>
<%= link_to t('links.category'), categories_path, class:"btn btn-primary btn-lg", role:"button" %>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= t('welcome') %></h1>
  <p class="lead"><%= t('welcome_msg') %></p>
  <hr class="my-4">
  <p><%= t('menu_msg') %></p>
   <%= render 'menu' %>
</div>